micronaut:
  application:
    name: trendingHashtagMicroservice
  serde:
    maximum-nesting-depth: 100
  server:
    port: 8080
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.trendingHashtags.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://${DB_HOST:db2}:3306/${DB_NAME:hashtags}
    username: todo
    password: todosecret
kafka:
  bootstrap:
    servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9092`}