micronaut:
  application:
    name: videoMicroservice
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://localhost:3306/books
    username: todo
    password: todosecret
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.videos.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers:
      - localhost:9094
      - localhost:9095
      - localhost:9096