micronaut:
  application:
    name: videoMicroservice
  serde:
    maximum-nesting-depth: 100
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://${DB_HOST:db}:3306/${DB_NAME:videos}
    username: ${DB_USER:todo}
    password: ${DB_PASSWORD:todosecret}
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.videos.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9192`}